language: node_js
node_js:
- '6'
services:
- mongodb
script: npm test
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: d/Zdg0siNeL7kuRnokPqZCiVm95672/AMdGuMSFQoT8bLGd0JZKewR8Ht3ftVwaFJqHjgeExoAUnZT4vcy3697FHRQHFt+qv0YaCOFQtFLTanHIDhf2ulW1+d67YwhQ93T8KNIIkV1APgb2PX1l+0BiUqwKcwm5C6MEDLhEBjXQrmwxszexQggYffWVYu4GHxQNp0tJTNUwb2CbnLzhO6KuqkVAQ3AerUzZoE+iAnz37y2oXz/VVToOy9f69SVQEuYjC07ma1qoOIBoR/IJXzgz62uQXBnw5q6/KILnjkr05f24jSF/TCW81M5/qYdsQLsEHjtClA66QfH8xtCpsbj54LbnsM47zxGTyMQ7sOh++1DBRi6R//amiuct3pj7dPxumwdhosqKVdlPelFKuB4CEdsIGms6aWpuaUE4apl3hFfQizmTj4DwpSwry8oeFa+e0doGWnY0e2UVGwYXxSVU/2MAApMPPx6TAspTwV+g+dUQxQvtIanExFuEKxJITTlaEOrmX5UCyKJzu53tdl+ef5MQawKx1Qc236Fpf9vvb460oWGWOimaXR2zjzcTB6P+dEiGx5q8FU/H1ns5dv05WoS9ABc6tOIZ0bk7oqu0ZjWuviQQWrEDCzInakkc8S6NpsQql3LQoXN0XSoEpi3myeOQJNDPJZ2dCD+Du3iA=
