language: node_js
node_js:
  - "6"
services:
  - mongodb
script: "npm test"
deploy:
  provider: heroku
  api_key:
    secure: VANoGiZYoELDOxUeT1QM2RCrn8tKhcg5kngxh18bXUKMzwQkghRa8wKG5HuRuExcW/64ssmao5yl3yh3HIgzRnvR1gIKok0sY+UBgdTDWbd6P/k+kF9qHnNN8pLSAkQf78WR0fyRH+gLB83TxahWS0cHI19sLEnEU3Pz7ZMnNHLXVjE2Oh+t0uPyFkqZzPUEoSAOGLlfILeWcBWchE8/oyBCWMqAi7+cMOJ3Beb+XBrIamUlQciAxamt8yTqlN7gGI5xofl0FNvoBng23yPtyu7GT/0tCT4aykicRzJHpTEdQ1OL9g7K3IAbO01ReoUp0Isv0WG5G5D2B+gUFntiQEtaQnPVX3vNeP9POk3iQBz1P/KE7d+9UrwOZth1JJIOOJ7GkShnSjS9SuW8oVSWrAuPTKtGDwuqTq5iyd2baCObFBzYAZgRuLi6fJvHGFPstkU90JByi9JOowgOZuQS2lR6Qr/CP1TXzBzfzEqByXIgAe47HDii+iaVTKDPahGBxSSerMsO+m2ajuOyI3AcIy6AZkCPI53B2r/27ufmNrSdJtfn633qcizWx8ttB28gduyG2AJKL0mt9j6rMDVAkQTl3qzlcWvSZgBsedX6+gGjXd6CWI1b9ES+6GyCCP6WV2FgFrlUC29hZPw3LCVDL6MjH0tMJVmhhd64Nqwjzy0=
